### ISSUE TITLE
Improve Matching Docs

### ISSUE THREAD

**Issue by mpaccione** [milesj/interweave#118]
Hey Miles, you've gone and created a convenient library here that intend to pair with react-syntax-highlighter to do code highlighting from old Wordpress posts in Gatbsy.

Good job!

That being said I have no damn clue how to do something very simple. Replace a tag like a "pre" tag with another tag. Your docs talk about custom matchers but this isn't custom at all... this is the direct use case of the library. I'm wonder where the TagMatch is...? The existing non custom Matchers also aren't listed upfront.

**Comment by milesj** [comment]
@mpaccione The pre-built matchers can be found under "Extensions", since they do more than just matching: https://milesj.gitbook.io/interweave/extensions/autolink

As for creating custom matchers, all the docs are here https://milesj.gitbook.io/interweave/matchers#creating-a-matcher If parts could be clarified more, let me know and I'll improve them.
